// Command openapi prints the default go-httpbin OpenAPI document as YAML.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"os"

	"github.com/mccutchen/go-httpbin/v2/httpbin"
	"go.yaml.in/yaml/v3"
)

const generatedHeader = "# Code generated by make openapi; DO NOT EDIT.\n"

func main() {
	if err := generate(os.Stdout); err != nil {
		log.Fatal(err)
	}
}

func generate(w io.Writer) error {
	req := httptest.NewRequest(http.MethodGet, "/openapi.json", nil)
	recorder := httptest.NewRecorder()
	httpbin.New().ServeHTTP(recorder, req)
	if recorder.Code != http.StatusOK {
		return fmt.Errorf("generate OpenAPI document: unexpected HTTP status %d", recorder.Code)
	}

	var document any
	if err := json.NewDecoder(recorder.Body).Decode(&document); err != nil {
		return fmt.Errorf("decode OpenAPI document: %w", err)
	}
	if _, err := io.WriteString(w, generatedHeader); err != nil {
		return fmt.Errorf("write generated header: %w", err)
	}

	encoder := yaml.NewEncoder(w)
	encoder.SetIndent(2)
	if err := encoder.Encode(document); err != nil {
		return fmt.Errorf("encode OpenAPI document: %w", err)
	}
	return nil
}
