package main

import (
	"bytes"
	"strings"
	"testing"

	"go.yaml.in/yaml/v3"
)

func TestGenerate(t *testing.T) {
	var output bytes.Buffer
	if err := generate(&output); err != nil {
		t.Fatal(err)
	}

	if !strings.HasPrefix(output.String(), "# Code generated by make openapi; DO NOT EDIT.\n") {
		t.Fatalf("missing generated-file header:\n%s", output.String())
	}

	var document struct {
		OpenAPI string                    `yaml:"openapi"`
		Servers []map[string]string       `yaml:"servers"`
		Paths   map[string]map[string]any `yaml:"paths"`
	}
	if err := yaml.Unmarshal(output.Bytes(), &document); err != nil {
		t.Fatal(err)
	}
	if document.OpenAPI != "3.2.0" {
		t.Fatalf("expected OpenAPI 3.2.0, got %q", document.OpenAPI)
	}
	if len(document.Servers) != 1 || document.Servers[0]["url"] != "/" {
		t.Fatalf("unexpected servers: %#v", document.Servers)
	}
	for path, method := range map[string]string{
		"/get":           "get",
		"/post":          "post",
		"/status/{code}": "get",
	} {
		if _, ok := document.Paths[path][method]; !ok {
			t.Errorf("generated document missing %s %s", method, path)
		}
	}
}
